//! Golden-fixture parity tests: the Rust implementation must reproduce the
//! Python bot's outputs on identical inputs.
//!
//! Fixtures are generated by `python scripts/gen_parity_fixtures.py` (repo
//! root), which runs the REAL Python implementation (live_trader_v2
//! _build_observation, reward fees, _process_fill, SB3 predict) on synthetic
//! scenarios. Tolerances: obs 1e-6, actions 1e-4 (f32 pipelines), fees and
//! fill accounting exact (both sides use ceil-to-cent and f64).

use serde_json::Value;

use kalshi_mm::book::TakerSide;
use kalshi_mm::config::MmParams;
use kalshi_mm::engine::plan_quotes;
use kalshi_mm::features::build_observation;
use kalshi_mm::model::Policy;
use kalshi_mm::state::{fill_fee, normalize_fill, TickerState, TraderState};

fn fixtures() -> Option<Value> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/parity.json");
    match std::fs::read_to_string(path) {
        Ok(text) => Some(serde_json::from_str(&text).expect("parity.json parses")),
        Err(_) => {
            eprintln!("SKIP: {path} missing — run `python scripts/gen_parity_fixtures.py`");
            None
        }
    }
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("number")
}

/// Build a TickerState exactly as the fixture generator populated Python's
/// parallel dicts for the same case.
fn ticker_state_from(case: &Value) -> TickerState {
    let mut ts = TickerState::new("KXADP");
    ts.book.load_snapshot(&serde_json::json!({
        "yes": case.get("yes").cloned().unwrap_or_else(|| Value::Array(vec![])),
        "no": case.get("no").cloned().unwrap_or_else(|| Value::Array(vec![])),
    }));
    ts.position = case.get("position").and_then(Value::as_i64).unwrap_or(0);
    ts.entry_price = case.get("entry_price").and_then(Value::as_f64);
    ts.fills_buy = case.get("fills_buy").and_then(Value::as_i64).unwrap_or(0);
    ts.fills_sell = case.get("fills_sell").and_then(Value::as_i64).unwrap_or(0);
    ts.realized_pnl = case.get("realized_pnl").and_then(Value::as_f64).unwrap_or(0.0);
    ts.last_mid_sample = case.get("last_mid_sample").and_then(Value::as_f64).unwrap_or(0.0);
    if let Some(hist) = case.get("mid_history").and_then(Value::as_array) {
        ts.mid_history = hist.iter().map(f).collect();
    }
    if let Some(trades) = case.get("recent_trades").and_then(Value::as_array) {
        ts.recent_trades = trades
            .iter()
            .map(|t| {
                let row = t.as_array().unwrap();
                let side = match row[2].as_str().unwrap() {
                    "yes" => TakerSide::Yes,
                    _ => TakerSide::No,
                };
                (f(&row[0]), row[1].as_i64().unwrap(), side)
            })
            .collect();
    }
    ts
}

#[test]
fn observations_match_python() {
    let Some(fx) = fixtures() else { return };
    let now_s = f(&fx["meta"]["now_s"]);
    let now_mono = f(&fx["meta"]["now_mono"]);
    let mm = MmParams::default();

    for case in fx["obs_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let mut ts = ticker_state_from(case);
        let obs = build_observation(name, &mut ts, &mm, now_s, now_mono);

        match (obs, case.get("expected_obs").filter(|v| !v.is_null())) {
            (None, None) => {} // both skipped — agreement
            (Some(got), Some(want)) => {
                let want = want.as_array().unwrap();
                for (i, (g, w)) in got.iter().zip(want).enumerate() {
                    let w = f(w);
                    assert!(
                        (f64::from(*g) - w).abs() < 1e-6,
                        "{name}: obs[{i}] rust={g} python={w}"
                    );
                }
                // The in-place mid-history maintenance must also agree
                let post = case["post_mid_history"].as_array().unwrap();
                assert_eq!(ts.mid_history.len(), post.len(), "{name}: mid_history length");
                for (g, w) in ts.mid_history.iter().zip(post) {
                    assert!((g - f(w)).abs() < 1e-9, "{name}: mid_history drift");
                }
            }
            (got, want) => panic!(
                "{name}: skip disagreement — rust={} python={}",
                got.is_some(),
                want.is_some()
            ),
        }
    }
}

#[test]
fn fees_match_python_exactly() {
    let Some(fx) = fixtures() else { return };
    for case in fx["fee_cases"].as_array().unwrap() {
        let got = fill_fee(f(&case["rate"]), case["contracts"].as_i64().unwrap(), f(&case["price"]));
        let want = f(&case["expected"]);
        assert_eq!(got, want, "fee case {case}");
    }
}

#[test]
fn fill_accounting_matches_python() {
    let Some(fx) = fixtures() else { return };
    for seq in fx["fill_sequences"].as_array().unwrap() {
        let name = seq["name"].as_str().unwrap();
        let mm = MmParams::default();
        let mut state = TraderState::new(0.0);
        let mut ticker = String::new();

        for fill in seq["fills"].as_array().unwrap() {
            let Some(nf) = normalize_fill(fill) else { continue };
            if state.seen_fill(&nf.fill_id) {
                continue;
            }
            ticker = nf.ticker.clone();
            let rate = if nf.is_taker { mm.taker_fee_rate } else { mm.maker_fee_rate };
            let fee = fill_fee(rate, nf.size, nf.price_yes);
            state.ticker(&nf.ticker.clone(), "KXADP");
            state.apply_fill(&ticker.clone(), &nf, fee, 0.0);
        }

        let want = &seq["expected"];
        let ts = &state.tickers[&ticker];
        assert_eq!(ts.position, want["position"].as_i64().unwrap(), "{name}: position");
        match want.get("entry_price").filter(|v| !v.is_null()) {
            Some(w) => assert!(
                (ts.entry_price.unwrap() - f(w)).abs() < 1e-12,
                "{name}: entry_price"
            ),
            None => assert_eq!(ts.entry_price, None, "{name}: entry_price should be cleared"),
        }
        assert!((state.daily_pnl - f(&want["daily_pnl"])).abs() < 1e-12, "{name}: daily_pnl");
        assert!((state.fees_paid - f(&want["fees_paid"])).abs() < 1e-12, "{name}: fees_paid");
        assert_eq!(state.wins, want["wins"].as_u64().unwrap(), "{name}: wins");
        assert_eq!(state.losses, want["losses"].as_u64().unwrap(), "{name}: losses");
        assert_eq!(state.taker_fills, want["taker_fills"].as_u64().unwrap(), "{name}: taker");
        assert_eq!(state.maker_fills, want["maker_fills"].as_u64().unwrap(), "{name}: maker");
        assert_eq!(state.fills, want["fills"].as_u64().unwrap(), "{name}: fills");
        assert!(
            (ts.realized_pnl - f(&want["realized_by_ticker"])).abs() < 1e-12,
            "{name}: realized_pnl"
        );
    }
}

#[test]
fn onnx_actions_match_sb3() {
    let Some(fx) = fixtures() else { return };
    // Committed alongside parity.json — rust/ carries its own copy of the
    // handful of ONNX policies these fixtures exercise, so the test needs
    // nothing from outside this directory.
    let models_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/models");

    // expected_obs by case name (actions were computed on these exact vectors)
    let mut obs_by_case = std::collections::HashMap::new();
    for case in fx["obs_cases"].as_array().unwrap() {
        if let Some(obs) = case.get("expected_obs").filter(|v| !v.is_null()) {
            let mut arr = [0f32; 20];
            for (i, v) in obs.as_array().unwrap().iter().enumerate() {
                arr[i] = f(v) as f32;
            }
            obs_by_case.insert(case["name"].as_str().unwrap().to_string(), arr);
        }
    }

    let mut policies: std::collections::HashMap<String, Policy> = std::collections::HashMap::new();
    let mut checked = 0;
    for case in fx["action_cases"].as_array().unwrap() {
        let model_name = case["model"].as_str().unwrap();
        let path = format!("{models_dir}/{model_name}.onnx");
        if !std::path::Path::new(&path).exists() {
            eprintln!("SKIP action case: {path} missing — run scripts/export_policy_onnx.py");
            continue;
        }
        let policy = policies
            .entry(model_name.to_string())
            .or_insert_with(|| Policy::load(&path).expect("policy loads"));
        let obs = obs_by_case[case["obs_case"].as_str().unwrap()];
        let got = policy.predict(&obs).expect("inference");
        let want = case["expected_action"].as_array().unwrap();
        for (g, w) in got.iter().zip(want) {
            assert!(
                (g - f(w)).abs() < 1e-4,
                "{model_name}/{}: action rust={got:?} python={want:?}",
                case["obs_case"]
            );
        }
        checked += 1;
    }
    assert!(checked > 0, "no ONNX action cases ran — export policies first");
}

/// plan_quotes must reproduce _execute_action's decisions exactly — cases
/// are generated by driving the REAL (unmodified) Python method through a
/// paper client, not a Python reimplementation of the Rust logic.
#[test]
fn quote_plan_matches_python() {
    let Some(fx) = fixtures() else { return };
    let mm = MmParams::default();
    const MAX_INVENTORY: i64 = 5; // KXADP in config/lowvol.toml

    for case in fx["quote_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let mut ts = TickerState::new(case["category"].as_str().unwrap());
        ts.book.load_snapshot(&case["book"]);
        ts.tick = f(&case["tick"]);
        ts.position = case["position"].as_i64().unwrap();
        ts.ever_quoted = case["ever_quoted"].as_bool().unwrap();
        ts.bid_order_id = case["bid_order_id"].as_str().map(String::from);
        ts.ask_order_id = case["ask_order_id"].as_str().map(String::from);
        if let Some(qp) = case["quoted_prices"].as_array() {
            ts.quoted_bid = Some(f(&qp[0]));
            ts.quoted_ask = Some(f(&qp[1]));
        }
        let open_order_count = case["open_order_count"].as_u64().unwrap() as usize;
        let backoff_until = f(&case["balance_backoff_until"]);

        let steps_in = case["steps_in"].as_array().unwrap();
        let steps_out = case["steps_out"].as_array().unwrap();
        for (step_idx, (step_in, step_out)) in steps_in.iter().zip(steps_out).enumerate() {
            let action_arr = step_in["action"].as_array().unwrap();
            let action = [f(&action_arr[0]), f(&action_arr[1])];
            let now_mono = f(&step_in["now_mono"]);

            let plan = plan_quotes(action, &mut ts, &mm, MAX_INVENTORY, open_order_count, backoff_until, now_mono);
            let skipped = step_out["skipped"].as_bool().unwrap();

            // plan_quotes is pure (no I/O); in production executor::apply_quote_plan
            // writes the result back onto TickerState after actually placing the
            // orders. Multi-step cases (e.g. throttle) need that same write-back
            // between steps, since step 3's tick-move-keep check depends on what
            // step 1 quoted — exactly like the real Python _execute_action, which
            // does decision + write-back in one fused call.
            if let Some(p) = &plan {
                ts.quoted_bid = Some(p.quoted_bid);
                ts.quoted_ask = Some(p.quoted_ask);
                ts.bid_order_id = p.place_bid.then(|| format!("{name}-{step_idx}-bid"));
                ts.ask_order_id = p.place_ask.then(|| format!("{name}-{step_idx}-ask"));
                ts.ever_quoted = true;
            }

            match (&plan, skipped) {
                (None, true) => {}
                (Some(p), false) => {
                    let want_bid = step_out["bid_cents"].as_f64();
                    let want_ask = step_out["ask_cents"].as_f64();
                    if let Some(w) = want_bid {
                        assert!((p.bid_cents - w).abs() < 1e-6, "{name}: bid_cents rust={} python={w}", p.bid_cents);
                    }
                    if let Some(w) = want_ask {
                        assert!((p.ask_cents - w).abs() < 1e-6, "{name}: ask_cents rust={} python={w}", p.ask_cents);
                    }
                    assert_eq!(p.place_bid, step_out["place_bid"].as_bool().unwrap(), "{name}: place_bid");
                    assert_eq!(p.place_ask, step_out["place_ask"].as_bool().unwrap(), "{name}: place_ask");

                    let mut got_cancels = p.cancel_ids.clone();
                    got_cancels.sort();
                    let mut want_cancels: Vec<String> = step_out["cancel_ids"]
                        .as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
                    want_cancels.sort();
                    assert_eq!(got_cancels, want_cancels, "{name}: cancel_ids");

                    assert!((p.quoted_bid - f(&step_out["quoted_bid"])).abs() < 1e-6, "{name}: quoted_bid");
                    assert!((p.quoted_ask - f(&step_out["quoted_ask"])).abs() < 1e-6, "{name}: quoted_ask");
                }
                (got, want_skip) => panic!(
                    "{name}: skip disagreement — rust_skipped={} python_skipped={want_skip}",
                    got.is_none()
                ),
            }

            let want_last_quote = step_out["post_last_quote_time"].as_f64();
            if let Some(w) = want_last_quote {
                assert!((ts.last_quote_time - w).abs() < 1e-9, "{name}: last_quote_time");
            }
        }
    }
}
